server:
  port: 8083
spring:
  application:
    name: redscarf-gateway-dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # 用户服务路由
        - id: redscarf-user-service-dev_1
          uri: http://localhost:8081
          predicates:
            - Path=/user-server/{param0}/{param1}/{param2}
        - id: redscarf-user-service-dev_2
          uri: http://localhost:8081
          predicates:
            - Path=/user-server/{param0}/{param1}

        # 帖子服务路由
        - id: redscarf-siege-service-dev_1
          uri: http://localhost:8082
          predicates:
            - Path=/siege-server/{param0}/{param1}/{param2}
        - id: redscarf-siege-service-dev_2
          uri: http://localhost:8082
          predicates:
            - Path=/siege-server/{param0}/{param1}

        ## item 服务路由
        - id: redscarf-item-service-dev_1
            uri: http://localhost:8084
            predicates:
              - Path=/item-server/{param0}/{param1}/{param2}
        - id: redscarf-item-service-dev_2
          uri: http://localhost:8084
          predicates:
            - Path=/item-server/{param0}/{param1}
        # 支付服务路由
        - id: redscarf-pay-service-dev_1
            uri: http://localhost:8085
            predicates:
              - Path=/pay-server/{param0}/{param1}/{param2}
        - id: redscarf-pay-service-dev_2
          uri: http://localhost:8085
          predicates:
            - Path=/pay-server/{param0}/{param1}