spring:
  cloud:
    sentinel:
      datasource:
        ns:
          nacos:
            serverAddr: 47.110.149.15:8848
            username: nacos
            password: nacos
            groupId: SENTINEL_GROUP
            dataId: ${spring.application.name}-flow-rules
            namespace: 016a7c5e-df72-45b2-925d-2a5046d5c0d1
            ruleType: flow
      transport:
        dashboard: 47.110.149.15:8080


